server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # DRUID
    url: jdbc:mysql://YOUR_IP:3306/literary_works_recommendation_platform  # MYSQL
    username: YOUR_USERNAME
    password: YOUR_PASS_WORD
  redis:
    host: YOUR_IP
    port: 6379
    database: 0
    password: YOUR_PASS_WORD

algorithm-backend:
  url: http://YOUR_ALGORITHM_BACKEND_IP:8000/

