spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB   # uploaded_file_size default 1MB max 10MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # Mapping: phone_number => phoneNumber
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # running log

  global-config:
    db-config:
      id-type: AUTO   # auto_increment
    banner: false

token:
  timeout: 336 #  336 hours = 14 days
